[package]
name = "hammerwork"
version = "0.1.0"
edition = "2024"
description = "A database-driven job queue for Rust with Postgres and MySQL support"
license = "MIT OR Apache-2.0"
repository = "https://github.com/CodingAnarchy/hammerwork"
authors = ["CodingAnarchy <noreply@codinganarchy.com>"]
homepage = "https://github.com/CodingAnarchy/hammerwork"
documentation = "https://docs.rs/hammerwork"
readme = "README.md"
keywords = ["database", "job-queue", "async", "postgres", "mysql"]
categories = ["database", "asynchronous", "concurrency"]

[dependencies]
tokio = { version = "1.0", features = ["full"] }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "chrono", "uuid", "json"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tracing = "0.1"
async-trait = "0.1"

[features]
default = []
postgres = ["sqlx/postgres"]
mysql = ["sqlx/mysql"]

[dev-dependencies]
tokio-test = "0.4"
