//! Core encryption engine implementation for Hammerwork.
//!
//! This module provides the actual cryptographic operations for encrypting and
//! decrypting job payloads using various algorithms and key management strategies.

use super::envelope::{self, DbStore, KmsKeyWrapper};
#[cfg(feature = "encryption")]
use super::key_manager::KeyManager;
use super::key_manager::KeyManagerBackend;
use super::{
    EncryptedPayload, EncryptionAlgorithm, EncryptionConfig, EncryptionError, EncryptionMetadata,
    EncryptionStats, KeySource, RetentionPolicy, kms,
};
use serde_json::Value;
use sqlx::{Database, Pool};
use std::collections::HashMap;
use std::sync::{Arc, Mutex};
use std::time::Instant;
use tracing::info;

#[cfg(feature = "encryption")]
use {
    aes_gcm::{Aes256Gcm, Key, KeyInit, Nonce, aead::Aead},
    base64::Engine,
    chacha20poly1305::{ChaCha20Poly1305, Key as ChaChaKey, Nonce as ChaChaNonce},
    rand::{RngCore, rngs::OsRng},
    sha2::{Digest, Sha256},
};

/// Core encryption engine for job payload encryption and decryption.
///
/// The engine manages encryption keys, provides encryption/decryption operations,
/// handles PII field detection and protection, and maintains statistics about
/// encryption operations.
///
/// # Thread Safety
///
/// The engine is designed to be used from multiple threads safely. Internal
/// state is protected with appropriate synchronization primitives.
///
/// The engine does not depend on a database backend: it works with PostgreSQL, MySQL or
/// no database at all. Only [`EncryptionEngine::new_with_pool`] and
/// [`EncryptionEngine::rotate_kms_key`] take a connection pool (PostgreSQL or MySQL), to
/// store KMS-wrapped data keys.
///
/// To encrypt job payloads at rest, give the engine to a queue with
/// [`JobQueue::with_encryption`](crate::JobQueue::with_encryption).
///
/// `aws://` and `gcp://` key sources use envelope encryption: the data key is generated by
/// the KMS once, stored KMS-encrypted in the database, and decrypted by the KMS on every
/// later start. Create engines for those sources with [`EncryptionEngine::new_with_pool`].
///
/// # Examples
///
/// ```rust,no_run
/// # #[cfg(feature = "encryption")]
/// # {
/// use hammerwork::encryption::{EncryptionAlgorithm, EncryptionConfig, EncryptionEngine, KeySource};
/// use serde_json::json;
///
/// #[tokio::main]
/// async fn main() -> Result<(), Box<dyn std::error::Error>> {
///     // HAMMERWORK_ENCRYPTION_KEY holds a base64-encoded 32-byte key
///     let config = EncryptionConfig::new(EncryptionAlgorithm::AES256GCM)
///         .with_key_source(KeySource::Environment("HAMMERWORK_ENCRYPTION_KEY".to_string()));
///     let engine = EncryptionEngine::new(config).await?;
///
///     let payload = json!({
///         "user_id": "123",
///         "credit_card": "4111-1111-1111-1111",
///         "amount": 99.99
///     });
///
///     let pii_fields = vec!["credit_card"];
///     let encrypted = engine.encrypt_payload(&payload, &pii_fields).await?;
///     let decrypted = engine.decrypt_payload(&encrypted).await?;
///
///     assert_eq!(payload, decrypted);
///     Ok(())
/// }
/// # }
/// ```
pub struct EncryptionEngine {
    config: EncryptionConfig,
    keys: Arc<Mutex<HashMap<String, Vec<u8>>>>,
    /// Earlier (rotated) versions of KMS-wrapped keys, newest first, used to decrypt
    /// payloads written before a rotation
    previous_keys: Arc<Mutex<HashMap<String, Vec<Vec<u8>>>>>,
    /// KMS that wraps the data key, for `aws://` and `gcp://` key sources
    kms: Option<Arc<dyn KmsKeyWrapper>>,
    stats: Arc<Mutex<EncryptionStats>>,
}

impl std::fmt::Debug for EncryptionEngine {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        // Never print key material
        f.debug_struct("EncryptionEngine")
            .field("algorithm", &self.config.algorithm)
            .field("key_id", &self.key_id())
            .finish_non_exhaustive()
    }
}

impl EncryptionEngine {
    /// Creates an encryption engine whose key may be persisted in the database.
    ///
    /// For `aws://` and `gcp://` key sources the data key uses envelope encryption: on
    /// first use the KMS generates it and only its KMS-encrypted form is stored in
    /// `hammerwork_kms_data_keys` (migration 017); later engines, in any process, read
    /// that blob and decrypt it with the KMS, so they all use the same key. Engines that
    /// start at the same time converge on one stored key. Earlier versions (see
    /// [`EncryptionEngine::rotate_kms_key`]) are loaded too, so payloads encrypted before
    /// a rotation can still be decrypted.
    ///
    /// Other key sources behave exactly as with [`EncryptionEngine::new`].
    ///
    /// # Examples
    ///
    /// ```rust,no_run
    /// # #[cfg(all(feature = "encryption", feature = "postgres"))]
    /// # {
    /// use hammerwork::encryption::{EncryptionAlgorithm, EncryptionConfig, EncryptionEngine, KeySource};
    ///
    /// # async fn example(pool: sqlx::PgPool) -> Result<(), hammerwork::encryption::EncryptionError> {
    /// let config = EncryptionConfig::new(EncryptionAlgorithm::AES256GCM).with_key_source(
    ///     KeySource::External("aws://alias/hammerwork?region=us-east-1".to_string()),
    /// );
    /// let engine = EncryptionEngine::new_with_pool(config, &pool).await?;
    /// # Ok(())
    /// # }
    /// # }
    /// ```
    pub async fn new_with_pool<DB: KeyManagerBackend>(
        config: EncryptionConfig,
        pool: &Pool<DB>,
    ) -> Result<Self, EncryptionError> {
        let kms = match envelope::parse_kms_source(&config.key_source)? {
            Some(source) => source.connect().await?,
            None => return Self::from_config(config).await,
        };
        Self::with_kms(config, pool, kms).await
    }

    /// Create an engine whose data key is wrapped by `kms` and stored in `pool`.
    async fn with_kms<DB: KeyManagerBackend>(
        config: EncryptionConfig,
        pool: &Pool<DB>,
        kms: Arc<dyn KmsKeyWrapper>,
    ) -> Result<Self, EncryptionError> {
        let key_id = config
            .key_id
            .clone()
            .unwrap_or_else(|| "default".to_string());
        let key_name = kms_key_name(&key_id);
        let size = config.key_size_bytes();
        let store = DbStore(pool);

        let active = envelope::load_or_create(&store, kms.as_ref(), &key_name, size).await?;
        let previous: Vec<Vec<u8>> = if active.version > 1 {
            envelope::load_all(&store, kms.as_ref(), &key_name, size)
                .await?
                .into_iter()
                .filter(|key| key.version != active.version)
                .map(|key| key.key)
                .collect()
        } else {
            Vec::new()
        };

        Ok(Self {
            config,
            keys: Arc::new(Mutex::new(HashMap::from([(key_id.clone(), active.key)]))),
            previous_keys: Arc::new(Mutex::new(HashMap::from([(key_id, previous)]))),
            kms: Some(kms),
            stats: Arc::new(Mutex::new(EncryptionStats::new())),
        })
    }

    /// Rotates a KMS-wrapped data key (`aws://` and `gcp://` key sources).
    ///
    /// The KMS generates a new data key; its KMS-encrypted form becomes the active version
    /// in `hammerwork_kms_data_keys` and the previous version is retired but kept. This
    /// engine encrypts with the new key from now on and can still decrypt payloads
    /// encrypted with earlier versions. Other engines pick up the new version when they
    /// are recreated.
    ///
    /// Returns the new version number. Fails with
    /// [`EncryptionError::InvalidConfiguration`] for engines not created by
    /// [`EncryptionEngine::new_with_pool`] with an `aws://` or `gcp://` source.
    pub async fn rotate_kms_key<DB: KeyManagerBackend>(
        &self,
        pool: &Pool<DB>,
    ) -> Result<u32, EncryptionError> {
        let kms = self.kms.clone().ok_or_else(|| {
            EncryptionError::InvalidConfiguration(
                "rotate_kms_key needs an engine created by new_with_pool with an aws:// or \
                 gcp:// key source"
                    .to_string(),
            )
        })?;
        let key_id = self
            .config
            .key_id
            .clone()
            .unwrap_or_else(|| "default".to_string());
        let rotated = envelope::rotate(
            &DbStore(pool),
            kms.as_ref(),
            &kms_key_name(&key_id),
            self.config.key_size_bytes(),
        )
        .await?;

        let lock_error =
            || EncryptionError::KeyManagement("Failed to acquire key lock".to_string());
        let old_key = self
            .keys
            .lock()
            .map_err(|_| lock_error())?
            .insert(key_id.clone(), rotated.key);
        if let Some(old_key) = old_key {
            self.previous_keys
                .lock()
                .map_err(|_| lock_error())?
                .entry(key_id)
                .or_default()
                .insert(0, old_key);
        }
        Ok(rotated.version)
    }
}

/// Name of an engine's KMS-wrapped data key in `hammerwork_kms_data_keys`.
fn kms_key_name(key_id: &str) -> String {
    format!("engine/{}", key_id)
}

// Constructors and key loading.
impl EncryptionEngine {
    /// Create an engine with the key named by `config.key_source`.
    async fn from_config(
        #[cfg_attr(not(feature = "encryption"), allow(unused_variables))] config: EncryptionConfig,
    ) -> Result<Self, EncryptionError> {
        #[cfg(not(feature = "encryption"))]
        {
            return Err(EncryptionError::InvalidConfiguration(
                "Encryption feature is not enabled. Enable the 'encryption' feature flag."
                    .to_string(),
            ));
        }

        #[cfg(feature = "encryption")]
        {
            let mut keys = HashMap::new();
            let key_id = config
                .key_id
                .clone()
                .unwrap_or_else(|| "default".to_string());

            // Load the encryption key
            let key = Self::load_key(&config.key_source, config.key_size_bytes()).await?;
            keys.insert(key_id, key);

            Ok(Self {
                config,
                keys: Arc::new(Mutex::new(keys)),
                previous_keys: Arc::new(Mutex::new(HashMap::new())),
                kms: None,
                stats: Arc::new(Mutex::new(EncryptionStats::new())),
            })
        }
    }

    #[cfg(feature = "encryption")]
    async fn store_generated_key(
        key_bytes: &[u8],
        location: &str,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        use base64::Engine;

        // Encode the key in base64 for storage
        let encoded_key = base64::engine::general_purpose::STANDARD.encode(key_bytes);

        // Determine storage method based on location format
        if location.starts_with("file://") {
            // Store in a file
            let file_path = location.strip_prefix("file://").unwrap_or(location);

            // Create directory if it doesn't exist
            if let Some(parent) = std::path::Path::new(file_path).parent() {
                std::fs::create_dir_all(parent)?;
            }

            // Write the key to file with restricted permissions
            use std::fs::OpenOptions;
            use std::io::Write;

            let mut file = OpenOptions::new()
                .create(true)
                .write(true)
                .truncate(true)
                .open(file_path)?;

            // Set restrictive permissions (owner read/write only)
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                let permissions = std::fs::Permissions::from_mode(0o600);
                file.set_permissions(permissions)?;
            }

            write!(file, "{}", encoded_key)?;
            file.flush()?;

            info!("Stored generated key in file: {}", file_path);
        } else if location.starts_with("env://") {
            // Store as environment variable (not recommended for production)
            let env_var = location.strip_prefix("env://").unwrap_or(location);
            unsafe {
                std::env::set_var(env_var, encoded_key);
            }

            info!("Stored generated key in environment variable: {}", env_var);
        } else if location.starts_with("stdout://") {
            // Print to stdout (useful for initial setup)
            println!("Generated encryption key: {}", encoded_key);
            println!("Store this key securely and set it as an environment variable.");
        } else {
            // Default to file storage
            let file_path = location;

            // Create directory if it doesn't exist
            if let Some(parent) = std::path::Path::new(file_path).parent() {
                std::fs::create_dir_all(parent)?;
            }

            use std::fs::OpenOptions;
            use std::io::Write;

            let mut file = OpenOptions::new()
                .create(true)
                .write(true)
                .truncate(true)
                .open(file_path)?;

            // Set restrictive permissions (owner read/write only)
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                let permissions = std::fs::Permissions::from_mode(0o600);
                file.set_permissions(permissions)?;
            }

            write!(file, "{}", encoded_key)?;
            file.flush()?;

            info!("Stored generated key in file: {}", file_path);
        }

        Ok(())
    }

    #[cfg(not(feature = "encryption"))]
    async fn store_generated_key(
        _key_bytes: &[u8],
        _location: &str,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        Err("Encryption feature is not enabled".into())
    }

    #[cfg(feature = "encryption")]
    async fn load_key(
        key_source: &KeySource,
        expected_size: usize,
    ) -> Result<Vec<u8>, EncryptionError> {
        match key_source {
            KeySource::Static(key_str) => {
                let key_bytes = base64::engine::general_purpose::STANDARD
                    .decode(key_str)
                    .map_err(|e| {
                        EncryptionError::KeyManagement(format!("Invalid base64 key: {}", e))
                    })?;

                if key_bytes.len() != expected_size {
                    return Err(EncryptionError::KeyManagement(format!(
                        "Key size mismatch: expected {} bytes, got {}",
                        expected_size,
                        key_bytes.len()
                    )));
                }

                Ok(key_bytes)
            }
            KeySource::Environment(var_name) => {
                let key_str = std::env::var(var_name).map_err(|_| {
                    EncryptionError::KeyManagement(format!(
                        "Environment variable {} not found",
                        var_name
                    ))
                })?;

                let key_bytes = base64::engine::general_purpose::STANDARD
                    .decode(&key_str)
                    .map_err(|e| {
                        EncryptionError::KeyManagement(format!(
                            "Invalid base64 key in {}: {}",
                            var_name, e
                        ))
                    })?;

                if key_bytes.len() != expected_size {
                    return Err(EncryptionError::KeyManagement(format!(
                        "Key size mismatch in {}: expected {} bytes, got {}",
                        var_name,
                        expected_size,
                        key_bytes.len()
                    )));
                }

                Ok(key_bytes)
            }
            KeySource::External(service_config) => {
                load_external_key(service_config, expected_size).await
            }
            KeySource::Generated(location) => {
                // Generate a new random key
                let mut key_bytes = vec![0u8; expected_size];
                OsRng.fill_bytes(&mut key_bytes);

                // Store the generated key in the specified location
                Self::store_generated_key(&key_bytes, location)
                    .await
                    .map_err(|e| {
                        EncryptionError::KeyManagement(format!(
                            "Failed to store generated key at {}: {}",
                            location, e
                        ))
                    })?;

                info!("Generated and stored new encryption key at: {}", location);
                Ok(key_bytes)
            }
        }
    }
}

impl EncryptionEngine {
    /// Creates a new encryption engine with the specified configuration.
    ///
    /// This will attempt to load the encryption key according to the
    /// configuration's key source. If the key cannot be loaded, an error
    /// will be returned.
    ///
    /// # Arguments
    ///
    /// * `config` - The encryption configuration to use
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - The encryption key cannot be loaded from the specified source
    /// - The encryption feature is not enabled
    /// - The configuration is invalid
    ///
    /// # Examples
    ///
    /// ```rust,no_run
    /// # #[cfg(feature = "encryption")]
    /// # {
    /// use hammerwork::encryption::{EncryptionEngine, EncryptionConfig, EncryptionAlgorithm, KeySource};
    ///
    /// # async fn example() -> Result<(), hammerwork::encryption::EncryptionError> {
    /// // With environment variable key (base64-encoded 32-byte key)
    /// let config = EncryptionConfig::new(EncryptionAlgorithm::AES256GCM)
    ///     .with_key_source(KeySource::Environment("MY_ENCRYPTION_KEY".to_string()));
    /// let engine = EncryptionEngine::new(config).await?;
    ///
    /// // With static key (for testing only)
    /// let config = EncryptionConfig::new(EncryptionAlgorithm::AES256GCM)
    ///     .with_key_source(KeySource::Static(
    ///         "QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUE=".to_string(),
    ///     ));
    /// let engine = EncryptionEngine::new(config).await?;
    /// # Ok(())
    /// # }
    /// # }
    /// ```
    pub async fn new(config: EncryptionConfig) -> Result<Self, EncryptionError> {
        Self::from_config(config).await
    }

    /// Adds a decrypt-only key, for payloads encrypted under another key id.
    ///
    /// The engine always encrypts with its configured key (`config.key_id`, or
    /// `"default"`). Each encrypted payload records the id of the key it was encrypted
    /// with; after switching to a new key id, add the previous key here so payloads
    /// written before the switch can still be decrypted.
    ///
    /// Fails if the key cannot be loaded or has the wrong size. Adding the engine's own
    /// key id is an error.
    ///
    /// # Examples
    ///
    /// ```rust,no_run
    /// # #[cfg(feature = "encryption")]
    /// # {
    /// use hammerwork::encryption::{EncryptionAlgorithm, EncryptionConfig, EncryptionEngine, KeySource};
    ///
    /// # async fn example() -> Result<(), hammerwork::encryption::EncryptionError> {
    /// let config = EncryptionConfig::new(EncryptionAlgorithm::AES256GCM)
    ///     .with_key_id("key-2026-10")
    ///     .with_key_source(KeySource::Environment("HAMMERWORK_KEY_2026_10".to_string()));
    /// let engine = EncryptionEngine::new(config)
    ///     .await?
    ///     .with_decryption_key(
    ///         "key-2026-04",
    ///         &KeySource::Environment("HAMMERWORK_KEY_2026_04".to_string()),
    ///     )
    ///     .await?;
    /// # Ok(())
    /// # }
    /// # }
    /// ```
    pub async fn with_decryption_key(
        self,
        key_id: impl Into<String>,
        key_source: &KeySource,
    ) -> Result<Self, EncryptionError> {
        let key_id = key_id.into();
        if key_id == self.key_id() {
            return Err(EncryptionError::InvalidConfiguration(format!(
                "Key id '{}' is the engine's encryption key",
                key_id
            )));
        }
        let key = Self::load_key(key_source, self.config.key_size_bytes()).await?;
        self.keys
            .lock()
            .map_err(|_| EncryptionError::KeyManagement("Failed to acquire key lock".to_string()))?
            .insert(key_id, key);
        Ok(self)
    }

    /// The engine's configuration.
    pub fn config(&self) -> &EncryptionConfig {
        &self.config
    }

    /// Id of the key the engine encrypts with (`config.key_id`, or `"default"`).
    pub fn key_id(&self) -> &str {
        self.config.key_id.as_deref().unwrap_or("default")
    }

    /// The algorithm the engine encrypts with.
    pub fn algorithm(&self) -> &EncryptionAlgorithm {
        &self.config.algorithm
    }

    /// The key used for encryption.
    fn active_key(&self) -> Result<Vec<u8>, EncryptionError> {
        let key_id = self.key_id();
        let keys = self.keys.lock().map_err(|_| {
            EncryptionError::KeyManagement("Failed to acquire key lock".to_string())
        })?;
        keys.get(key_id)
            .cloned()
            .ok_or_else(|| EncryptionError::KeyManagement(format!("Key not found: {}", key_id)))
    }

    /// Encrypts a job payload with optional PII field protection.
    ///
    /// This method encrypts the entire payload and optionally applies special
    /// handling to fields containing personally identifiable information (PII).
    /// PII fields are tracked in the encryption metadata for compliance purposes.
    ///
    /// # Arguments
    ///
    /// * `payload` - The JSON payload to encrypt
    /// * `pii_fields` - List of field names that contain PII
    ///
    /// # Returns
    ///
    /// An encrypted payload container with all necessary metadata for decryption.
    ///
    /// # Examples
    ///
    /// ```rust,no_run
    /// # #[cfg(feature = "encryption")]
    /// # {
    /// use serde_json::json;
    ///
    /// # async fn example(engine: hammerwork::encryption::EncryptionEngine) -> Result<(), Box<dyn std::error::Error>> {
    /// let payload = json!({
    ///     "user_id": "123",
    ///     "email": "user@example.com",
    ///     "ssn": "123-45-6789",
    ///     "amount": 99.99
    /// });
    ///
    /// let pii_fields = vec!["email", "ssn"];
    /// let encrypted = engine.encrypt_payload(&payload, &pii_fields).await?;
    /// # Ok(())
    /// # }
    /// # }
    /// ```
    pub async fn encrypt_payload(
        &self,
        payload: &Value,
        pii_fields: &[impl AsRef<str>],
    ) -> Result<EncryptedPayload, EncryptionError> {
        self.encrypt_payload_with_retention(payload, pii_fields, RetentionPolicy::UseDefault)
            .await
    }

    /// Encrypts a job payload with a custom retention policy.
    ///
    /// Similar to `encrypt_payload` but allows specifying a custom retention
    /// policy for this specific payload.
    ///
    /// # Arguments
    ///
    /// * `payload` - The JSON payload to encrypt
    /// * `pii_fields` - List of field names that contain PII
    /// * `retention_policy` - Custom retention policy for this payload
    pub async fn encrypt_payload_with_retention(
        &self,
        payload: &Value,
        pii_fields: &[impl AsRef<str>],
        retention_policy: RetentionPolicy,
    ) -> Result<EncryptedPayload, EncryptionError> {
        let result = self.encrypt_value(payload, pii_fields, retention_policy);
        if result.is_err()
            && let Ok(mut stats) = self.stats.lock()
        {
            stats.record_encryption_error();
        }
        result
    }

    fn encrypt_value(
        &self,
        payload: &Value,
        pii_fields: &[impl AsRef<str>],
        retention_policy: RetentionPolicy,
    ) -> Result<EncryptedPayload, EncryptionError> {
        let start_time = Instant::now();
        let key = self.active_key()?;

        let payload_bytes = serde_json::to_vec(payload).map_err(EncryptionError::Serialization)?;

        // Keyed integrity hash of the plaintext. It is stored next to the ciphertext, so it
        // must not be a plain digest: a SHA-256 of a low-entropy value (an SSN, a card
        // number) can be reversed by brute force.
        let payload_hash = keyed_payload_hash(&key, &payload_bytes)?;

        let data_to_encrypt = if self.config.compression_enabled {
            self.compress_data(&payload_bytes)?
        } else {
            payload_bytes
        };

        let (ciphertext, nonce, tag) = self.encrypt_data(&key, &data_to_encrypt)?;

        let pii_field_names: Vec<String> =
            pii_fields.iter().map(|f| f.as_ref().to_string()).collect();

        let mut metadata = EncryptionMetadata::new(
            &self.config,
            pii_field_names.clone(),
            retention_policy,
            payload_hash,
        );
        metadata.key_id = self.key_id().to_string();
        metadata.delete_at = metadata.retention_policy.calculate_deletion_time(
            metadata.encrypted_at,
            None,
            self.config.default_retention,
        );

        let duration_ms = start_time.elapsed().as_millis() as f64;
        if let Ok(mut stats) = self.stats.lock() {
            stats.record_encryption(&self.config.algorithm, data_to_encrypt.len(), duration_ms);
            stats.record_pii_encryption(pii_field_names.len());
        }

        Ok(EncryptedPayload::new(ciphertext, nonce, tag, metadata))
    }

    /// Decrypts an encrypted payload back to its original JSON form.
    ///
    /// This method handles key lookup, algorithm selection, decompression,
    /// and integrity verification automatically based on the metadata
    /// contained in the encrypted payload.
    ///
    /// # Arguments
    ///
    /// * `encrypted_payload` - The encrypted payload to decrypt
    ///
    /// # Returns
    ///
    /// The original JSON payload.
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - The decryption key is not available
    /// - The ciphertext has been corrupted
    /// - The algorithm is not supported
    /// - The integrity check fails
    ///
    /// # Examples
    ///
    /// ```rust,no_run
    /// # #[cfg(feature = "encryption")]
    /// # {
    /// # async fn example(engine: hammerwork::encryption::EncryptionEngine, encrypted_payload: hammerwork::encryption::EncryptedPayload) -> Result<(), Box<dyn std::error::Error>> {
    /// let decrypted_payload = engine.decrypt_payload(&encrypted_payload).await?;
    /// println!("Decrypted: {}", decrypted_payload);
    /// # Ok(())
    /// # }
    /// # }
    /// ```
    pub async fn decrypt_payload(
        &self,
        encrypted_payload: &EncryptedPayload,
    ) -> Result<Value, EncryptionError> {
        let result = self.decrypt_value(encrypted_payload);
        if result.is_err()
            && let Ok(mut stats) = self.stats.lock()
        {
            stats.record_decryption_error();
        }
        result
    }

    fn decrypt_value(
        &self,
        encrypted_payload: &EncryptedPayload,
    ) -> Result<Value, EncryptionError> {
        let start_time = Instant::now();
        let lock_error =
            || EncryptionError::KeyManagement("Failed to acquire key lock".to_string());

        // The key named by the payload, then earlier versions of a rotated KMS-wrapped key
        let key_id = &encrypted_payload.metadata.key_id;
        let mut candidates = vec![
            self.keys
                .lock()
                .map_err(|_| lock_error())?
                .get(key_id)
                .cloned()
                .ok_or_else(|| {
                    EncryptionError::KeyManagement(format!(
                        "Key not found: {} (the payload was encrypted with a key this engine \
                         does not have; see EncryptionEngine::with_decryption_key)",
                        key_id
                    ))
                })?,
        ];
        candidates.extend(
            self.previous_keys
                .lock()
                .map_err(|_| lock_error())?
                .get(key_id)
                .cloned()
                .unwrap_or_default(),
        );

        let ciphertext = encrypted_payload.decode_ciphertext()?;
        let nonce = encrypted_payload.decode_nonce()?;
        let tag = encrypted_payload.decode_tag()?;
        let algorithm = &encrypted_payload.metadata.algorithm;

        let mut first_error = None;
        let mut decrypted = None;
        for key in &candidates {
            match self.decrypt_data(&ciphertext, &nonce, &tag, key, algorithm) {
                Ok(data) => {
                    decrypted = Some((key, data));
                    break;
                }
                Err(err) => {
                    first_error.get_or_insert(err);
                }
            }
        }
        let (key, decrypted_data) = match decrypted {
            Some(found) => found,
            None => {
                return Err(first_error.unwrap_or_else(|| {
                    EncryptionError::DecryptionFailed("no key could decrypt the payload".into())
                }));
            }
        };

        let payload_bytes = if encrypted_payload.metadata.compressed {
            self.decompress_data(&decrypted_data)?
        } else {
            decrypted_data
        };

        // Verify integrity. Payloads written before keyed hashes carry a plain SHA-256.
        let expected = &encrypted_payload.metadata.payload_hash;
        let calculated = if expected.starts_with(KEYED_HASH_PREFIX) {
            keyed_payload_hash(key, &payload_bytes)?
        } else {
            self.calculate_payload_hash(&payload_bytes)
        };
        if calculated != *expected {
            return Err(EncryptionError::DecryptionFailed(
                "Payload integrity check failed".to_string(),
            ));
        }

        let payload: Value =
            serde_json::from_slice(&payload_bytes).map_err(EncryptionError::Serialization)?;

        let duration_ms = start_time.elapsed().as_millis() as f64;
        if let Ok(mut stats) = self.stats.lock() {
            stats.record_decryption(payload_bytes.len(), duration_ms);
        }

        Ok(payload)
    }

    /// Identifies PII fields in a JSON payload based on field names and patterns.
    ///
    /// This method scans the payload for common PII field names and patterns
    /// to automatically identify fields that should be encrypted.
    ///
    /// # Arguments
    ///
    /// * `payload` - The JSON payload to scan
    ///
    /// # Returns
    ///
    /// A list of field names that likely contain PII.
    ///
    /// # Examples
    ///
    /// ```rust
    /// # #[cfg(feature = "encryption")]
    /// # {
    /// use serde_json::json;
    ///
    /// # fn example(engine: &hammerwork::encryption::EncryptionEngine) {
    /// let payload = json!({
    ///     "user_id": "123",
    ///     "email": "user@example.com",
    ///     "credit_card_number": "4111-1111-1111-1111",
    ///     "amount": 99.99
    /// });
    ///
    /// let pii_fields = engine.identify_pii_fields(&payload);
    /// // Returns: ["email", "credit_card_number"]
    /// # }
    /// # }
    /// ```
    pub fn identify_pii_fields(&self, payload: &Value) -> Vec<String> {
        let mut pii_fields = Vec::new();

        // Common PII field name patterns
        let pii_patterns = [
            "ssn",
            "social_security",
            "social_security_number",
            "credit_card",
            "credit_card_number",
            "card_number",
            "cc_number",
            "email",
            "email_address",
            "e_mail",
            "phone",
            "phone_number",
            "telephone",
            "mobile",
            "passport",
            "passport_number",
            "driver_license",
            "drivers_license",
            "license_number",
            "bank_account",
            "account_number",
            "routing_number",
            "password",
            "secret",
            "private_key",
            "address",
            "street_address",
            "home_address",
            "date_of_birth",
            "birth_date",
            "dob",
            "tax_id",
            "taxpayer_id",
            "ein",
        ];

        self.scan_object_for_pii(payload, &pii_patterns, &mut pii_fields, "");
        pii_fields
    }

    /// Gets the current encryption statistics.
    ///
    /// # Examples
    ///
    /// ```rust
    /// # #[cfg(feature = "encryption")]
    /// # {
    /// # fn example(engine: &hammerwork::encryption::EncryptionEngine) {
    /// let stats = engine.get_stats();
    /// println!("Jobs encrypted: {}", stats.jobs_encrypted);
    /// println!("Success rate: {:.2}%", stats.encryption_success_rate());
    /// # }
    /// # }
    /// ```
    pub fn get_stats(&self) -> EncryptionStats {
        self.stats
            .lock()
            .map(|stats| stats.clone())
            .unwrap_or_else(|_| {
                // If lock is poisoned, return default stats
                EncryptionStats::new()
            })
    }

    /// Formerly attached a [`KeyManager`] to the engine. The engine never used it, so
    /// this does nothing.
    #[deprecated(
        since = "1.16.0",
        note = "the engine never used the key manager; this method has no effect"
    )]
    pub fn set_key_manager<DB: Database>(&mut self, key_manager: Arc<Mutex<KeyManager<DB>>>) {
        let _ = key_manager;
    }

    /// Cleans up expired encrypted data based on retention policies.
    ///
    /// This method should be called periodically to remove encrypted
    /// payloads that have exceeded their retention period.
    ///
    /// # Arguments
    ///
    /// * `encrypted_payloads` - List of encrypted payloads to check
    ///
    /// # Returns
    ///
    /// The number of payloads that should be deleted.
    pub fn cleanup_expired_data(&self, encrypted_payloads: &[EncryptedPayload]) -> usize {
        let expired_count = encrypted_payloads
            .iter()
            .filter(|payload| payload.should_delete_now())
            .count();

        if expired_count > 0
            && let Ok(mut stats) = self.stats.lock()
        {
            stats.record_retention_cleanup(expired_count as u64);
        }

        expired_count
    }

    // Private helper methods

    #[allow(clippy::type_complexity)]
    fn encrypt_data(
        &self,
        key: &[u8],
        data: &[u8],
    ) -> Result<(Vec<u8>, Vec<u8>, Vec<u8>), EncryptionError> {
        check_key_size(key)?;
        match self.config.algorithm {
            EncryptionAlgorithm::AES256GCM => {
                let cipher_key = Key::<Aes256Gcm>::from_slice(key);
                let cipher = Aes256Gcm::new(cipher_key);

                // Generate random nonce
                let mut nonce_bytes = vec![0u8; 12];
                OsRng.fill_bytes(&mut nonce_bytes);
                let nonce = Nonce::from_slice(&nonce_bytes);

                // Encrypt the data
                let ciphertext_with_tag = cipher.encrypt(nonce, data).map_err(|e| {
                    EncryptionError::EncryptionFailed(format!("AES encryption failed: {}", e))
                })?;

                // Split ciphertext and tag
                let tag_start = ciphertext_with_tag.len() - 16;
                let ciphertext = ciphertext_with_tag[..tag_start].to_vec();
                let tag = ciphertext_with_tag[tag_start..].to_vec();

                Ok((ciphertext, nonce_bytes, tag))
            }
            EncryptionAlgorithm::ChaCha20Poly1305 => {
                let cipher_key = ChaChaKey::from_slice(key);
                let cipher = ChaCha20Poly1305::new(cipher_key);

                // Generate random nonce
                let mut nonce_bytes = vec![0u8; 12];
                OsRng.fill_bytes(&mut nonce_bytes);
                let nonce = ChaChaNonce::from_slice(&nonce_bytes);

                // Encrypt the data
                let ciphertext_with_tag = cipher.encrypt(nonce, data).map_err(|e| {
                    EncryptionError::EncryptionFailed(format!("ChaCha20 encryption failed: {}", e))
                })?;

                // Split ciphertext and tag
                let tag_start = ciphertext_with_tag.len() - 16;
                let ciphertext = ciphertext_with_tag[..tag_start].to_vec();
                let tag = ciphertext_with_tag[tag_start..].to_vec();

                Ok((ciphertext, nonce_bytes, tag))
            }
        }
    }

    #[cfg(feature = "encryption")]
    fn decrypt_data(
        &self,
        ciphertext: &[u8],
        nonce: &[u8],
        tag: &[u8],
        key: &[u8],
        algorithm: &EncryptionAlgorithm,
    ) -> Result<Vec<u8>, EncryptionError> {
        // The nonce and tag come from storage: reject wrong sizes instead of panicking
        // in `from_slice`.
        check_key_size(key)?;
        if nonce.len() != NONCE_SIZE || tag.len() != TAG_SIZE {
            return Err(EncryptionError::DecryptionFailed(format!(
                "Invalid nonce or tag size ({} and {} bytes, expected {} and {})",
                nonce.len(),
                tag.len(),
                NONCE_SIZE,
                TAG_SIZE
            )));
        }

        // Reconstruct the ciphertext with tag
        let mut ciphertext_with_tag = ciphertext.to_vec();
        ciphertext_with_tag.extend_from_slice(tag);

        match algorithm {
            EncryptionAlgorithm::AES256GCM => {
                let cipher_key = Key::<Aes256Gcm>::from_slice(key);
                let cipher = Aes256Gcm::new(cipher_key);
                let nonce = Nonce::from_slice(nonce);

                cipher
                    .decrypt(nonce, ciphertext_with_tag.as_slice())
                    .map_err(|e| {
                        EncryptionError::DecryptionFailed(format!("AES decryption failed: {}", e))
                    })
            }
            EncryptionAlgorithm::ChaCha20Poly1305 => {
                let cipher_key = ChaChaKey::from_slice(key);
                let cipher = ChaCha20Poly1305::new(cipher_key);
                let nonce = ChaChaNonce::from_slice(nonce);

                cipher
                    .decrypt(nonce, ciphertext_with_tag.as_slice())
                    .map_err(|e| {
                        EncryptionError::DecryptionFailed(format!(
                            "ChaCha20 decryption failed: {}",
                            e
                        ))
                    })
            }
        }
    }

    #[cfg(feature = "encryption")]
    fn compress_data(&self, data: &[u8]) -> Result<Vec<u8>, EncryptionError> {
        use flate2::{Compression, write::GzEncoder};
        use std::io::Write;

        let mut encoder = GzEncoder::new(Vec::new(), Compression::default());
        encoder
            .write_all(data)
            .map_err(|e| EncryptionError::FieldProcessing(format!("Compression failed: {}", e)))?;
        encoder.finish().map_err(|e| {
            EncryptionError::FieldProcessing(format!("Compression finalization failed: {}", e))
        })
    }

    #[cfg(feature = "encryption")]
    fn decompress_data(&self, data: &[u8]) -> Result<Vec<u8>, EncryptionError> {
        use flate2::read::GzDecoder;
        use std::io::Read;

        let mut decoder = GzDecoder::new(data);
        let mut decompressed = Vec::new();
        decoder.read_to_end(&mut decompressed).map_err(|e| {
            EncryptionError::FieldProcessing(format!("Decompression failed: {}", e))
        })?;
        Ok(decompressed)
    }

    #[cfg(feature = "encryption")]
    fn calculate_payload_hash(&self, data: &[u8]) -> String {
        let mut hasher = Sha256::new();
        hasher.update(data);
        hex::encode(hasher.finalize())
    }

    #[allow(clippy::only_used_in_recursion)]
    fn scan_object_for_pii(
        &self,
        value: &Value,
        patterns: &[&str],
        pii_fields: &mut Vec<String>,
        prefix: &str,
    ) {
        match value {
            Value::Object(map) => {
                for (key, val) in map {
                    let field_name = if prefix.is_empty() {
                        key.clone()
                    } else {
                        format!("{}.{}", prefix, key)
                    };

                    // Check if this key matches any PII patterns
                    let key_lower = key.to_lowercase();
                    if patterns.iter().any(|pattern| {
                        key_lower.contains(pattern)
                            || key_lower
                                .replace('_', "")
                                .contains(&pattern.replace('_', ""))
                    }) {
                        pii_fields.push(field_name.clone());
                    }

                    // Recursively scan nested objects
                    if matches!(val, Value::Object(_)) {
                        self.scan_object_for_pii(val, patterns, pii_fields, &field_name);
                    }
                }
            }
            Value::Array(arr) => {
                for (i, val) in arr.iter().enumerate() {
                    let field_name = format!("{}[{}]", prefix, i);
                    if matches!(val, Value::Object(_)) {
                        self.scan_object_for_pii(val, patterns, pii_fields, &field_name);
                    }
                }
            }
            _ => {} // Primitive values don't contain nested fields
        }
    }
}

/// Nonce size of both supported AEAD algorithms.
const NONCE_SIZE: usize = 12;
/// Authentication tag size of both supported AEAD algorithms.
const TAG_SIZE: usize = 16;
/// Key size of both supported AEAD algorithms.
const KEY_SIZE: usize = 32;
/// Prefix of keyed payload hashes (`EncryptionMetadata::payload_hash`).
const KEYED_HASH_PREFIX: &str = "hmac-sha256:";

fn check_key_size(key: &[u8]) -> Result<(), EncryptionError> {
    if key.len() == KEY_SIZE {
        Ok(())
    } else {
        Err(EncryptionError::KeyManagement(format!(
            "Invalid key size: expected {} bytes, got {}",
            KEY_SIZE,
            key.len()
        )))
    }
}

/// HMAC-SHA256 of `data` under a key derived from the data key, as
/// `hmac-sha256:<hex>`.
fn keyed_payload_hash(key: &[u8], data: &[u8]) -> Result<String, EncryptionError> {
    use hmac::{Hmac, Mac};

    // Derive a separate MAC key so the data key itself is never used outside the AEAD.
    let mac_key = Sha256::new()
        .chain_update(b"hammerwork payload hash v1")
        .chain_update(key)
        .finalize();
    let mut mac = <Hmac<Sha256> as Mac>::new_from_slice(&mac_key)
        .map_err(|e| EncryptionError::Cryptographic(format!("HMAC key error: {}", e)))?;
    mac.update(data);
    Ok(format!(
        "{}{}",
        KEYED_HASH_PREFIX,
        hex::encode(mac.finalize().into_bytes())
    ))
}

// External key loaders. They fail closed: an unavailable KMS, missing credentials or a
// KMS source whose cargo feature is not enabled is an error, never a fallback key.

/// Load a key from the external key management service named by `service_config`.
async fn load_external_key(
    service_config: &str,
    expected_size: usize,
) -> Result<Vec<u8>, EncryptionError> {
    if service_config.starts_with("aws://") || service_config.starts_with("gcp://") {
        // Validates the configuration and the cargo feature first
        envelope::parse_kms_source(&KeySource::External(service_config.to_string()))?;
        Err(EncryptionError::InvalidConfiguration(format!(
            "{} keys are generated once by the KMS and stored KMS-encrypted in the database; \
             create the engine with EncryptionEngine::new_with_pool",
            &service_config[..service_config.find("://").unwrap_or(0) + 3]
        )))
    } else if service_config.starts_with("vault://") {
        load_from_vault(service_config, expected_size).await
    } else if service_config.starts_with("azure://") {
        load_from_azure_kv(service_config, expected_size).await
    } else {
        Err(EncryptionError::KeyManagement(format!(
            "Unknown external key management service: {}",
            service_config
        )))
    }
}

/// Load a key from a HashiCorp Vault KV v2 secret (`vault://<mount>/<path>?addr=<url>`).
///
/// The secret's string `key` field is used: a base64 key is truncated or padded to
/// `expected_size`, any other string is hashed with SHA-256.
async fn load_from_vault(
    service_config: &str,
    expected_size: usize,
) -> Result<Vec<u8>, EncryptionError> {
    let (secret_path, params) = kms::parse_service_config(service_config, "vault://");
    let vault_addr = kms::vault_address(&params)?;
    let (mount, secret) = kms::vault_mount_and_path(secret_path)?;

    info!(
        "Loading key from HashiCorp Vault: path={}, addr={}",
        secret_path, vault_addr
    );

    #[cfg(not(feature = "vault-kms"))]
    {
        let _ = (mount, secret, expected_size);
        Err(kms::kms_feature_disabled("vault://", "vault-kms"))
    }

    #[cfg(feature = "vault-kms")]
    {
        let key_str = kms::vault_read_key_field(&vault_addr, mount, secret).await?;

        if let Ok(decoded) = base64::engine::general_purpose::STANDARD.decode(&key_str) {
            if decoded.len() == expected_size {
                info!("Successfully loaded encryption key from HashiCorp Vault");
                return Ok(decoded);
            }
            // Wrong size: truncate, or pad with a hash of the decoded key
            let mut key = vec![0u8; expected_size];
            let copy_len = std::cmp::min(decoded.len(), expected_size);
            key[..copy_len].copy_from_slice(&decoded[..copy_len]);
            if decoded.len() < expected_size {
                let hash = Sha256::digest(&decoded);
                for (i, byte) in key.iter_mut().enumerate().skip(decoded.len()) {
                    *byte = hash[i % hash.len()];
                }
            }
            info!("Successfully loaded and resized encryption key from HashiCorp Vault");
            return Ok(key);
        }

        // Not base64: hash the string to the expected size
        let hash = Sha256::digest(key_str.as_bytes());
        let key = (0..expected_size).map(|i| hash[i % hash.len()]).collect();
        info!("Successfully loaded and hashed encryption key from HashiCorp Vault");
        Ok(key)
    }
}

/// Load a key from Azure Key Vault (`azure://<vault-host>/keys/<key-name>`, key name
/// defaults to `encryption-key`). Material shorter than `expected_size` is padded with
/// HMAC-SHA256 output keyed by the material.
async fn load_from_azure_kv(
    service_config: &str,
    expected_size: usize,
) -> Result<Vec<u8>, EncryptionError> {
    let (vault_url, key_name) = kms::azure_vault_and_key(service_config, "encryption-key")?;

    info!(
        "Loading key from Azure Key Vault: vault={}, key={}",
        vault_url, key_name
    );

    #[cfg(not(feature = "azure-kv"))]
    {
        let _ = (vault_url, key_name, expected_size);
        Err(kms::kms_feature_disabled("azure://", "azure-kv"))
    }

    #[cfg(feature = "azure-kv")]
    {
        let decoded_key = super::azure::fetch_key_material(&vault_url, &key_name)
            .await
            .map_err(|e| {
                EncryptionError::KeyManagement(format!(
                    "Failed to load key from Azure Key Vault: {}",
                    e
                ))
            })?;

        if decoded_key.len() >= expected_size {
            info!("Successfully loaded encryption key from Azure Key Vault");
            return Ok(decoded_key[..expected_size].to_vec());
        }

        // Key is shorter than expected: pad it using key derivation
        use hmac::{Hmac, Mac};
        type HmacSha256 = Hmac<Sha256>;

        let mut final_key = vec![0u8; expected_size];
        final_key[..decoded_key.len()].copy_from_slice(&decoded_key);

        let mut mac = <HmacSha256 as Mac>::new_from_slice(&decoded_key)
            .map_err(|e| EncryptionError::KeyManagement(format!("HMAC creation failed: {}", e)))?;
        mac.update(b"azure-kv-key-derivation");
        mac.update(vault_url.as_bytes());
        mac.update(key_name.as_bytes());
        let derived = mac.finalize().into_bytes();

        for (i, byte) in final_key.iter_mut().enumerate().skip(decoded_key.len()) {
            *byte = derived[i % derived.len()];
        }

        info!("Successfully loaded and padded encryption key from Azure Key Vault");
        Ok(final_key)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;
    use std::time::Duration;

    #[cfg(feature = "encryption")]
    #[tokio::test]
    async fn test_encryption_engine_creation() {
        // Set up a test key in environment
        unsafe {
            std::env::set_var(
                "TEST_ENCRYPTION_KEY",
                "dGVzdGtleTE5ODc2NTQzMjEwOTg3NjU0MzIxMHRlc3Q=",
            ); // 32 bytes base64
        }

        let config = EncryptionConfig::new(EncryptionAlgorithm::AES256GCM)
            .with_key_source(KeySource::Environment("TEST_ENCRYPTION_KEY".to_string()));

        let engine = EncryptionEngine::new(config).await;
        assert!(engine.is_ok());
    }

    #[cfg(feature = "encryption")]
    #[tokio::test]
    async fn test_payload_encryption_decryption() {
        unsafe {
            std::env::set_var(
                "TEST_ENCRYPTION_KEY",
                "dGVzdGtleTE5ODc2NTQzMjEwOTg3NjU0MzIxMHRlc3Q=",
            );
        }

        let config = EncryptionConfig::new(EncryptionAlgorithm::AES256GCM)
            .with_key_source(KeySource::Environment("TEST_ENCRYPTION_KEY".to_string()));

        let engine = EncryptionEngine::new(config).await.unwrap();

        let payload = json!({
            "user_id": "123",
            "email": "test@example.com",
            "amount": 99.99
        });

        let pii_fields = vec!["email"];
        let encrypted = engine.encrypt_payload(&payload, &pii_fields).await.unwrap();
        let decrypted = engine.decrypt_payload(&encrypted).await.unwrap();

        assert_eq!(payload, decrypted);
        assert!(encrypted.contains_pii_field("email"));
        assert!(!encrypted.contains_pii_field("user_id"));
    }

    #[tokio::test]
    async fn test_pii_field_identification() {
        let config = EncryptionConfig::new(EncryptionAlgorithm::AES256GCM);
        let engine = EncryptionEngine::new(config).await;

        // This test doesn't require the encryption feature to be enabled for PII detection
        if engine.is_err() {
            return; // Skip if encryption feature not enabled
        }

        let engine = engine.unwrap();

        let payload = json!({
            "user_id": "123",
            "email": "test@example.com",
            "credit_card_number": "4111-1111-1111-1111",
            "ssn": "123-45-6789",
            "amount": 99.99,
            "metadata": {
                "phone_number": "+1-555-123-4567"
            }
        });

        let pii_fields = engine.identify_pii_fields(&payload);

        assert!(pii_fields.contains(&"email".to_string()));
        assert!(pii_fields.contains(&"credit_card_number".to_string()));
        assert!(pii_fields.contains(&"ssn".to_string()));
        assert!(pii_fields.contains(&"metadata.phone_number".to_string()));
        assert!(!pii_fields.contains(&"user_id".to_string()));
        assert!(!pii_fields.contains(&"amount".to_string()));
    }

    #[cfg(feature = "encryption")]
    #[tokio::test]
    async fn test_encryption_with_compression() {
        unsafe {
            std::env::set_var(
                "TEST_ENCRYPTION_KEY",
                "dGVzdGtleTE5ODc2NTQzMjEwOTg3NjU0MzIxMHRlc3Q=",
            );
        }

        let config = EncryptionConfig::new(EncryptionAlgorithm::AES256GCM)
            .with_key_source(KeySource::Environment("TEST_ENCRYPTION_KEY".to_string()))
            .with_compression_enabled(true);

        let engine = EncryptionEngine::new(config).await.unwrap();

        let payload = json!({
            "data": "a".repeat(1000), // Large repeating data that compresses well
            "user_id": "123"
        });

        let encrypted = engine
            .encrypt_payload(&payload, &Vec::<String>::new())
            .await
            .unwrap();
        let decrypted = engine.decrypt_payload(&encrypted).await.unwrap();

        assert_eq!(payload, decrypted);
        assert!(encrypted.metadata.compressed);
    }

    #[cfg(feature = "encryption")]
    #[tokio::test]
    async fn test_encryption_stats() {
        unsafe {
            std::env::set_var(
                "TEST_ENCRYPTION_KEY",
                "dGVzdGtleTE5ODc2NTQzMjEwOTg3NjU0MzIxMHRlc3Q=",
            );
        }

        let config = EncryptionConfig::new(EncryptionAlgorithm::AES256GCM)
            .with_key_source(KeySource::Environment("TEST_ENCRYPTION_KEY".to_string()));

        let engine = EncryptionEngine::new(config).await.unwrap();

        let payload = json!({"test": "data"});

        let initial_stats = engine.get_stats();
        assert_eq!(initial_stats.jobs_encrypted, 0);

        let _encrypted = engine.encrypt_payload(&payload, &["test"]).await.unwrap();

        let stats = engine.get_stats();
        assert_eq!(stats.jobs_encrypted, 1);
        assert_eq!(stats.pii_fields_encrypted, 1);
        assert!(stats.avg_encryption_time_ms >= 0.0);
    }

    #[tokio::test]
    async fn test_retention_policy_cleanup() {
        let config = EncryptionConfig::new(EncryptionAlgorithm::AES256GCM);
        let engine = EncryptionEngine::new(config).await;

        if engine.is_err() {
            return; // Skip if encryption feature not enabled
        }

        let engine = engine.unwrap();

        // Create a mock encrypted payload with immediate deletion policy
        let metadata = EncryptionMetadata::new(
            &EncryptionConfig::default(),
            vec![],
            RetentionPolicy::DeleteAfter(Duration::from_secs(1)),
            "test_hash".to_string(),
        );

        let payload = EncryptedPayload::new(
            b"test".to_vec(),
            b"nonce".to_vec(),
            b"tag".to_vec(),
            metadata,
        );

        // Should not be expired immediately
        assert!(!payload.should_delete_now());

        // Wait for expiration (in a real test, we'd mock the time)
        tokio::time::sleep(Duration::from_millis(1100)).await;

        let expired_count = engine.cleanup_expired_data(&[payload]);
        assert_eq!(expired_count, 1);
    }

    fn static_engine(key_id: &str, key: &str) -> EncryptionConfig {
        EncryptionConfig::new(EncryptionAlgorithm::AES256GCM)
            .with_key_id(key_id)
            .with_key_source(KeySource::Static(key.to_string()))
    }

    const KEY_A: &str = "dGVzdGtleTE5ODc2NTQzMjEwOTg3NjU0MzIxMHRlc3Q=";
    const KEY_B: &str = "QUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUE=";

    #[tokio::test]
    async fn test_decryption_key_for_previous_key_id() {
        let old = EncryptionEngine::new(static_engine("old", KEY_A))
            .await
            .unwrap();
        let payload = json!({"ssn": "123-45-6789"});
        let encrypted = old.encrypt_payload(&payload, &["ssn"]).await.unwrap();
        assert_eq!(encrypted.metadata.key_id, "old");

        let new = EncryptionEngine::new(static_engine("new", KEY_B))
            .await
            .unwrap();
        assert!(matches!(
            new.decrypt_payload(&encrypted).await,
            Err(EncryptionError::KeyManagement(_))
        ));

        let new = new
            .with_decryption_key("old", &KeySource::Static(KEY_A.to_string()))
            .await
            .unwrap();
        assert_eq!(new.decrypt_payload(&encrypted).await.unwrap(), payload);
        // New payloads still use the engine's own key
        let fresh = new.encrypt_payload(&payload, &["ssn"]).await.unwrap();
        assert_eq!(fresh.metadata.key_id, "new");
        assert!(old.decrypt_payload(&fresh).await.is_err());

        // The engine's own key id cannot be replaced
        assert!(matches!(
            new.with_decryption_key("new", &KeySource::Static(KEY_A.to_string()))
                .await,
            Err(EncryptionError::InvalidConfiguration(_))
        ));
    }

    #[tokio::test]
    async fn test_payload_hash_is_keyed() {
        let engine = EncryptionEngine::new(static_engine("k", KEY_A))
            .await
            .unwrap();
        let payload = json!({"ssn": "123-45-6789"});
        let encrypted = engine.encrypt_payload(&payload, &["ssn"]).await.unwrap();

        // Not the plain SHA-256 of the plaintext, which could be brute-forced
        let plain = engine.calculate_payload_hash(&serde_json::to_vec(&payload).unwrap());
        assert!(encrypted.metadata.payload_hash.starts_with("hmac-sha256:"));
        assert!(!encrypted.metadata.payload_hash.contains(&plain));

        // A different key gives a different hash
        let other = EncryptionEngine::new(static_engine("k", KEY_B))
            .await
            .unwrap();
        let other_encrypted = other.encrypt_payload(&payload, &["ssn"]).await.unwrap();
        assert_ne!(
            encrypted.metadata.payload_hash,
            other_encrypted.metadata.payload_hash
        );

        // Tampering with the hash is detected
        let mut tampered = encrypted.clone();
        tampered.metadata.payload_hash = format!("hmac-sha256:{}", "0".repeat(64));
        assert!(matches!(
            engine.decrypt_payload(&tampered).await,
            Err(EncryptionError::DecryptionFailed(_))
        ));
    }

    #[tokio::test]
    async fn test_legacy_unkeyed_hash_still_decrypts() {
        let engine = EncryptionEngine::new(static_engine("k", KEY_A))
            .await
            .unwrap();
        let payload = json!({"a": 1});
        let mut encrypted = engine.encrypt_payload(&payload, &["a"]).await.unwrap();
        encrypted.metadata.payload_hash =
            engine.calculate_payload_hash(&serde_json::to_vec(&payload).unwrap());
        assert_eq!(engine.decrypt_payload(&encrypted).await.unwrap(), payload);
    }

    #[tokio::test]
    async fn test_bad_nonce_or_tag_is_an_error_not_a_panic() {
        use base64::Engine as _;
        let engine = EncryptionEngine::new(static_engine("k", KEY_A))
            .await
            .unwrap();
        let encrypted = engine
            .encrypt_payload(&json!({"a": 1}), &["a"])
            .await
            .unwrap();

        let mut short_nonce = encrypted.clone();
        short_nonce.nonce = base64::engine::general_purpose::STANDARD.encode([0u8; 4]);
        assert!(engine.decrypt_payload(&short_nonce).await.is_err());

        let mut short_tag = encrypted.clone();
        short_tag.tag = base64::engine::general_purpose::STANDARD.encode([0u8; 3]);
        assert!(engine.decrypt_payload(&short_tag).await.is_err());
        assert_eq!(engine.get_stats().decryption_errors, 2);
    }

    #[tokio::test]
    async fn test_debug_does_not_print_keys() {
        let engine = EncryptionEngine::new(static_engine("k", KEY_A))
            .await
            .unwrap();
        let debug = format!("{:?}", engine);
        assert!(debug.contains("AES256GCM"));
        assert!(!debug.contains(KEY_A));
        assert!(!debug.contains("116, 101, 115, 116")); // "test" as key bytes
    }

    // ---- Fail-closed external key loading (#16); no cloud credentials needed ----

    #[tokio::test]
    async fn test_external_key_invalid_config_fails() {
        let cases = [
            "aws://?region=us-east-1",
            "vault://key-only?addr=http://127.0.0.1:1",
            "gcp://not-a-resource",
            "azure://",
        ];
        for source in cases {
            let err = load_external_key(source, 32).await.unwrap_err();
            assert!(
                matches!(err, EncryptionError::InvalidConfiguration(_)),
                "{source}: {err}"
            );
        }
        let err = load_external_key("ftp://key", 32).await.unwrap_err();
        assert!(matches!(err, EncryptionError::KeyManagement(_)), "{err}");
    }

    #[tokio::test]
    async fn test_external_key_without_feature_fails() {
        #[allow(unused_mut)]
        let mut cases: Vec<(&str, &str)> = Vec::new();
        #[cfg(not(feature = "aws-kms"))]
        cases.push(("aws://alias/key?region=us-east-1", "aws-kms"));
        #[cfg(not(feature = "vault-kms"))]
        cases.push(("vault://secret/key?addr=http://127.0.0.1:1", "vault-kms"));
        #[cfg(not(feature = "gcp-kms"))]
        cases.push((
            "gcp://projects/p/locations/global/keyRings/r/cryptoKeys/k",
            "gcp-kms",
        ));
        #[cfg(not(feature = "azure-kv"))]
        cases.push(("azure://my-vault.vault.azure.net/keys/k", "azure-kv"));

        for (source, feature) in cases {
            let err = load_external_key(source, 32).await.unwrap_err();
            assert!(
                matches!(err, EncryptionError::InvalidConfiguration(_)),
                "{source}: {err}"
            );
            assert!(err.to_string().contains(feature), "{source}: {err}");
        }
    }

    /// Without a database there is nowhere to keep the KMS-wrapped key, so `new` refuses
    /// `aws://` and `gcp://` sources instead of generating a key per process (#26).
    #[tokio::test]
    async fn test_kms_source_without_pool_fails() {
        #[allow(unused_mut)]
        let mut cases: Vec<&str> = Vec::new();
        #[cfg(feature = "aws-kms")]
        cases.push("aws://alias/key?region=us-east-1");
        #[cfg(feature = "gcp-kms")]
        cases.push("gcp://projects/p/locations/global/keyRings/r/cryptoKeys/k");
        for source in cases {
            let err = load_external_key(source, 32).await.unwrap_err();
            assert!(
                matches!(err, EncryptionError::InvalidConfiguration(_)),
                "{source}: {err}"
            );
            assert!(err.to_string().contains("new_with_pool"), "{source}: {err}");
        }
    }

    #[cfg(feature = "vault-kms")]
    #[tokio::test]
    async fn test_vault_key_unavailable_fails() {
        let result = load_from_vault("vault://secret/hammerwork?addr=http://127.0.0.1:1", 32).await;
        assert!(matches!(result, Err(EncryptionError::KeyManagement(_))));
    }

    // ---- KMS-wrapped data keys (#26), with a local mock KMS ----

    use crate::encryption::envelope::test_support::MockKms;

    fn same_kms(kms: &MockKms) -> Arc<dyn KmsKeyWrapper> {
        Arc::new(MockKms::new(kms.kms_key_id(), [0x5a; 32]))
    }

    fn active_key(engine: &EncryptionEngine, key_id: &str) -> Vec<u8> {
        engine.keys.lock().unwrap()[key_id].clone()
    }

    fn previous_keys(engine: &EncryptionEngine, key_id: &str) -> Vec<Vec<u8>> {
        engine
            .previous_keys
            .lock()
            .unwrap()
            .get(key_id)
            .cloned()
            .unwrap_or_default()
    }

    /// Engines in different processes (or after a restart) load the same stored data key,
    /// and keep earlier versions after a rotation.
    async fn engine_kms_roundtrip<DB: KeyManagerBackend>(pool: Pool<DB>) {
        let kms = MockKms::unique();
        let config = || EncryptionConfig::new(EncryptionAlgorithm::AES256GCM);

        let first = EncryptionEngine::with_kms(config(), &pool, same_kms(&kms))
            .await
            .unwrap();
        let v1 = active_key(&first, "default");
        assert_eq!(v1.len(), 32);

        // Restart: the same key is recovered from the stored KMS-wrapped blob
        let second = EncryptionEngine::with_kms(config(), &pool, same_kms(&kms))
            .await
            .unwrap();
        assert_eq!(active_key(&second, "default"), v1);
        assert!(previous_keys(&second, "default").is_empty());

        assert_eq!(second.rotate_kms_key(&pool).await.unwrap(), 2);
        let v2 = active_key(&second, "default");
        assert_ne!(v1, v2);
        assert_eq!(previous_keys(&second, "default"), vec![v1.clone()]);

        let third = EncryptionEngine::with_kms(config(), &pool, same_kms(&kms))
            .await
            .unwrap();
        assert_eq!(active_key(&third, "default"), v2);
        assert_eq!(previous_keys(&third, "default"), vec![v1.clone()]);

        // Another key id is a separate key
        let other =
            EncryptionEngine::with_kms(config().with_key_id("other"), &pool, same_kms(&kms))
                .await
                .unwrap();
        assert_ne!(active_key(&other, "other"), v1);
        assert_ne!(active_key(&other, "other"), v2);

        let stored = DB::load_kms_wrapped_keys(&pool, "engine/default", "aws", kms.kms_key_id())
            .await
            .unwrap();
        assert_eq!(stored.len(), 2);

        // rotate_kms_key needs a KMS source
        let static_engine = EncryptionEngine::new_with_pool(
            config().with_key_source(KeySource::Static(
                "dGVzdGtleTE5ODc2NTQzMjEwOTg3NjU0MzIxMHRlc3Q=".to_string(),
            )),
            &pool,
        )
        .await
        .unwrap();
        assert!(matches!(
            static_engine.rotate_kms_key(&pool).await,
            Err(EncryptionError::InvalidConfiguration(_))
        ));
    }

    /// Engines starting at the same time converge on one stored data key.
    async fn engine_kms_concurrent_first_load<DB: KeyManagerBackend>(pool: Pool<DB>) {
        let kms = MockKms::unique();
        let tasks: Vec<_> = (0..6)
            .map(|_| {
                let pool = pool.clone();
                let kms = same_kms(&kms);
                tokio::spawn(async move {
                    let config = EncryptionConfig::new(EncryptionAlgorithm::AES256GCM);
                    let engine = EncryptionEngine::with_kms(config, &pool, kms)
                        .await
                        .unwrap();
                    active_key(&engine, "default")
                })
            })
            .collect();
        let mut keys = Vec::new();
        for task in tasks {
            keys.push(task.await.unwrap());
        }
        assert!(keys.windows(2).all(|w| w[0] == w[1]));
        let stored = DB::load_kms_wrapped_keys(&pool, "engine/default", "aws", kms.kms_key_id())
            .await
            .unwrap();
        assert_eq!(stored.len(), 1);
    }

    /// Payloads encrypted before a restart and before a rotation can be decrypted.
    async fn engine_kms_payload_roundtrip<DB: KeyManagerBackend>(pool: Pool<DB>) {
        let kms = MockKms::unique();
        let config = || EncryptionConfig::new(EncryptionAlgorithm::AES256GCM);
        let payload = json!({"ssn": "123-45-6789", "amount": 10});

        let first = EncryptionEngine::with_kms(config(), &pool, same_kms(&kms))
            .await
            .unwrap();
        let before_rotation = first.encrypt_payload(&payload, &["ssn"]).await.unwrap();

        let second = EncryptionEngine::with_kms(config(), &pool, same_kms(&kms))
            .await
            .unwrap();
        assert_eq!(
            second.decrypt_payload(&before_rotation).await.unwrap(),
            payload
        );
        second.rotate_kms_key(&pool).await.unwrap();
        let after_rotation = second.encrypt_payload(&payload, &["ssn"]).await.unwrap();
        assert_eq!(
            second.decrypt_payload(&before_rotation).await.unwrap(),
            payload
        );

        let third = EncryptionEngine::with_kms(config(), &pool, same_kms(&kms))
            .await
            .unwrap();
        assert_eq!(
            third.decrypt_payload(&before_rotation).await.unwrap(),
            payload
        );
        assert_eq!(
            third.decrypt_payload(&after_rotation).await.unwrap(),
            payload
        );
        // The engine that did not rotate cannot read the new version until it reloads
        assert!(first.decrypt_payload(&after_rotation).await.is_err());
    }

    #[cfg(feature = "postgres")]
    async fn postgres_pool() -> sqlx::PgPool {
        use crate::migrations::{MigrationManager, postgres::PostgresMigrationRunner};
        let url = std::env::var("DATABASE_URL")
            .expect("DATABASE_URL must point at a PostgreSQL test database");
        let pool = sqlx::PgPool::connect(&url).await.unwrap();
        MigrationManager::new(Box::new(PostgresMigrationRunner::new(pool.clone())))
            .run_migrations()
            .await
            .unwrap();
        pool
    }

    #[cfg(feature = "mysql")]
    async fn mysql_pool() -> sqlx::MySqlPool {
        use crate::migrations::{MigrationManager, mysql::MySqlMigrationRunner};
        let url = std::env::var("MYSQL_DATABASE_URL")
            .expect("MYSQL_DATABASE_URL must point at a MySQL test database");
        let pool = sqlx::MySqlPool::connect(&url).await.unwrap();
        MigrationManager::new(Box::new(MySqlMigrationRunner::new(pool.clone())))
            .run_migrations()
            .await
            .unwrap();
        pool
    }

    #[cfg(feature = "postgres")]
    #[tokio::test]
    #[ignore = "requires PostgreSQL: DATABASE_URL"]
    async fn test_engine_kms_payload_roundtrip_postgres() {
        engine_kms_payload_roundtrip(postgres_pool().await).await;
    }

    #[cfg(feature = "mysql")]
    #[tokio::test]
    #[ignore = "requires MySQL: MYSQL_DATABASE_URL"]
    async fn test_engine_kms_payload_roundtrip_mysql() {
        engine_kms_payload_roundtrip(mysql_pool().await).await;
    }

    #[cfg(feature = "postgres")]
    #[tokio::test]
    #[ignore = "requires PostgreSQL: DATABASE_URL"]
    async fn test_engine_kms_roundtrip_postgres() {
        engine_kms_roundtrip(postgres_pool().await).await;
    }

    #[cfg(feature = "mysql")]
    #[tokio::test]
    #[ignore = "requires MySQL: MYSQL_DATABASE_URL"]
    async fn test_engine_kms_roundtrip_mysql() {
        engine_kms_roundtrip(mysql_pool().await).await;
    }

    #[cfg(feature = "postgres")]
    #[tokio::test]
    #[ignore = "requires PostgreSQL: DATABASE_URL"]
    async fn test_engine_kms_concurrent_first_load_postgres() {
        engine_kms_concurrent_first_load(postgres_pool().await).await;
    }

    #[cfg(feature = "mysql")]
    #[tokio::test]
    #[ignore = "requires MySQL: MYSQL_DATABASE_URL"]
    async fn test_engine_kms_concurrent_first_load_mysql() {
        engine_kms_concurrent_first_load(mysql_pool().await).await;
    }
}
